CREATE TABLE [DatoClinico] (
[id] INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL,
[nome] VARCHAR(20)  NULL,
[tipo] VARCHAR(15)  NULL,
[io] VARCHAR(10)  NULL
);

CREATE TABLE [Paziente] (
[id] INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL,
[patient_name] VARCHAR(40)  NULL,
[cartella_immagini] VARCHAR(40)  NULL
);

CREATE TABLE [DatoClinico_Paziente] (
[id] INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL,
[id_dato_clinico] INTEGER  REFERENCES DatoClinico(id) ON DELETE CASCADE,
[id_paziente] INTEGER  REFERENCES Paziente(id) ON DELETE CASCADE,
[valore] VARCHAR(40)  NULL
);

CREATE TABLE [ROI] (
[id] INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT,
[nome] VARCHAR(30)  NULL
);

CREATE TABLE [ROI_ROIPaziente] (
[id] INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT,
[id_roi] INTEGER  REFERENCES ROI(id) ON DELETE CASCADE,
[id_paziente] INTEGER  REFERENCES Paziente(id) ON DELETE CASCADE,
[nome_roi_paziente] VARCHAR(40)  NULL
);
